export const envConfig = {
  KAKAO_API_KEY: process.env.REACT_APP_KAKAO_API_KEY,
  KAKAO_REDIRECT_URI: process.env.REACT_APP_KAKAO_REDIRECT_URI,
  BASE_URL: process.env.REACT_APP_BASE_URL,
  SOLVEDAC_URL: process.env.REACT_APP_SOLVEDAC_URL,
  GITHUB_URL: process.env.REACT_APP_GITHUB_URL,
};
